<?php

namespace EventsBundle\Repository;

/**
 * PublicityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicityRepository extends \Doctrine\ORM\EntityRepository
{
}
