list_product:
    path:     /products
    defaults: { _controller: ProductBundle:Default:products }


shop:
    path:     /shop
    defaults: { _controller: ProductBundle:Default:frontshop }

shop-single:
    path:     /shop-single
    defaults: { _controller: ProductBundle:Default:frontshopsingle}

list_products:
    path:     /productList
    defaults: { _controller: ProductBundle:Default:productList }

affect_promotion:
    path:     /affectPromotion/{id}
    defaults: { _controller: ProductBundle:Default:affectPromotion }

list_promotion:
    path:     /listPromotion
    defaults: { _controller: ProductBundle:Default:listPromotion }

delete_promotion:
    path:     /deletePromotion/{id}
    defaults: { _controller: ProductBundle:Default:deletePromotion }

Modify_promotion:
    path:     /modifierPromotion/{id}
    defaults: { _controller: ProductBundle:Default:modifierPromotion }
