user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

admin_homepage:
    path:     /admin
    defaults: { _controller: UserBundle:Default:admin }

client_homepage:
    path:     /client
    defaults: { _controller: UserBundle:Default:client }